#ifndef CONSTANTS_MAP_SEC_H
#define CONSTANTS_MAP_SEC_H

#define MAPSEC_PALLET_TOWN                  0x58
#define MAPSEC_VIRIDIAN_CITY                0x59
#define MAPSEC_PEWTER_CITY                  0x5A
#define MAPSEC_CERULEAN_CITY                0x5B
#define MAPSEC_LAVENDER_TOWN                0x5C
#define MAPSEC_VERMILION_CITY               0x5D
#define MAPSEC_CELADON_CITY                 0x5E
#define MAPSEC_FUCHSIA_CITY                 0x5F
#define MAPSEC_CINNABAR_ISLAND              0x60
#define MAPSEC_INDIGO_PLATEAU               0x61
#define MAPSEC_SAFFRON_CITY                 0x62
#define MAPSEC_ROUTE_26	                    0x63
#define MAPSEC_ROUTE_27		                0x64
#define MAPSEC_ROUTE_1                      0x65
#define MAPSEC_ROUTE_2                      0x66
#define MAPSEC_ROUTE_3                      0x67
#define MAPSEC_ROUTE_4                      0x68
#define MAPSEC_ROUTE_5                      0x69
#define MAPSEC_ROUTE_6                      0x6A
#define MAPSEC_ROUTE_7                      0x6B
#define MAPSEC_ROUTE_8                      0x6C
#define MAPSEC_ROUTE_9                      0x6D
#define MAPSEC_ROUTE_10                     0x6E
#define MAPSEC_ROUTE_11                     0x6F
#define MAPSEC_ROUTE_12                     0x70
#define MAPSEC_ROUTE_13                     0x71
#define MAPSEC_ROUTE_14                     0x72
#define MAPSEC_ROUTE_15                     0x73
#define MAPSEC_ROUTE_16                     0x74
#define MAPSEC_ROUTE_17                     0x75
#define MAPSEC_ROUTE_18                     0x76
#define MAPSEC_ROUTE_19                     0x77
#define MAPSEC_ROUTE_20                     0x78
#define MAPSEC_ROUTE_21                     0x79
#define MAPSEC_ROUTE_22                     0x7A
#define MAPSEC_ROUTE_23                     0x7B
#define MAPSEC_ROUTE_24                     0x7C
#define MAPSEC_ROUTE_25                     0x7D
#define MAPSEC_VIRIDIAN_FOREST              0x7E
#define MAPSEC_MT_MOON                      0x7F
#define MAPSEC_ROUTE_28                     0x80
#define MAPSEC_UNDERGROUND_PATH             0x81
#define MAPSEC_PAL_PARK                     0x82
#define MAPSEC_DIGLETTS_CAVE                0x83
#define MAPSEC_VICTORY_ROAD                 0x84
#define MAPSEC_ROCKET_HIDEOUT               0x85
#define MAPSEC_SILPH_CO                     0x86
#define MAPSEC_TOHJO_FALLS                  0x87
#define MAPSEC_SAFARI_ZONE                  0x88
#define MAPSEC_POKEMON_LEAGUE               0x89
#define MAPSEC_ROCK_TUNNEL                  0x8A
#define MAPSEC_SEAFOAM_ISLANDS              0x8B
#define MAPSEC_KANTO_RADIO_TOWER            0x8C
#define MAPSEC_CERULEAN_CAVE                0x8D
#define MAPSEC_POWER_PLANT                  0x8E

#define MAPSEC_GOLDENROD_CITY               0x8F
#define MAPSEC_CHERRYGROVE_CITY             0x8F
#define MAPSEC_VIOLET_CITY                  0x90
#define MAPSEC_AZALEA_TOWN                  0x91
#define MAPSEC_BLACKTHORN_CITY              0x92
#define MAPSEC_ECRUTEAK_CITY                0x93
#define MAPSEC_OLIVINE_CITY                 0x94
#define MAPSEC_CIANWOOD_CITY                0x95
#define MAPSEC_MAHOGANY_TOWN                0x96
#define MAPSEC_NEW_BARK_TOWN                0x97
#define MAPSEC_SAFARI_ZONE_GATE             0x98
#define MAPSEC_ROUTE_46                     0x99
#define MAPSEC_ROUTE_47                     0x9A
#define MAPSEC_ROUTE_48                     0x9B
#define MAPSEC_ROUTE_29                     0x9C
#define MAPSEC_ROUTE_30                     0x9D
#define MAPSEC_ROUTE_31                     0x9E
#define MAPSEC_ROUTE_32                     0x9F
#define MAPSEC_ROUTE_33                     0xA0
#define MAPSEC_ROUTE_34                     0xA1
#define MAPSEC_ROUTE_35                     0xA2
#define MAPSEC_ROUTE_36                     0xA3
#define MAPSEC_ROUTE_37                     0xA4
#define MAPSEC_ROUTE_38                     0xA5
#define MAPSEC_ROUTE_39                     0xA6
#define MAPSEC_ROUTE_40                     0xA7
#define MAPSEC_ROUTE_41                     0xA8
#define MAPSEC_ROUTE_42                     0xA9
#define MAPSEC_ROUTE_43                     0xAA
#define MAPSEC_ROUTE_44                     0xAB
#define MAPSEC_ROUTE_45                     0xAC
#define MAPSEC_GOLDENROD_TUNNEL             0xAD
#define MAPSEC_DARK_CAVE                    0xAE
#define MAPSEC_SPROUT_TOWER                 0xAF
#define MAPSEC_RUINS_OF_ALPH                0xB0
#define MAPSEC_UNION_CAVE                   0xB1
#define MAPSEC_BATTLE_TOWER                 0xB2
#define MAPSEC_SLOWPOKE_WELL                0xB3
#define MAPSEC_ILEX_FOREST                  0xB4
#define MAPSEC_RADIO_TOWER                  0xB5
#define MAPSEC_LAKE_OF_RAGE                 0xB6
#define MAPSEC_DRAGONS_DEN                  0xB7
#define MAPSEC_LAKE_OFRAGE_2                0xB8
#define MAPSEC_Mt_SILVER                    0xB9
#define MAPSEC_SILVER_CAVE                  0xBA
#define MAPSEC_NATIONAL_PARK                0xBB
#define MAPSEC_BELL_TOWER                   0xBC
#define MAPSEC_BURNED_TOWER                 0xBD
#define MAPSEC_GLITTER_LIGHTHOUSE           0xBF
#define MAPSEC_WHIRL_ISLANDS                0xC0
#define MAPSEC_MT_MORTAR                    0xC1
#define MAPSEC_TEAM_ROCKET_HQ               0xC2
#define MAPSEC_ICE_PATH                     0xC3
#define MAPSEC_CELADON_DEPART               0xC4
#define MAPSEC_NONE                         0xC5
#define MAPSEC_COUNT                        0xC6

#endif //CONSTANTS_MAP_SEC_H
